version: '3.8'

services:
  smar-mcp:
    build: .
    container_name: smar-mcp-server
    environment:
      - SMARTSHEET_API_KEY=${SMARTSHEET_API_KEY}
      - SMARTSHEET_ENDPOINT=${SMARTSHEET_ENDPOINT:-https://api.smartsheet.com/2.0}
      - ALLOW_DELETE_TOOLS=${ALLOW_DELETE_TOOLS:-false}
      - NODE_ENV=production
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      # Mount a volume for logs if needed
      - ./logs:/app/logs
    networks:
      - smar-mcp-network

  # Optional: Add a development service for local development
  smar-mcp-dev:
    build:
      context: .
      target: development
    container_name: smar-mcp-dev
    environment:
      - SMARTSHEET_API_KEY=${SMARTSHEET_API_KEY}
      - SMARTSHEET_ENDPOINT=${SMARTSHEET_ENDPOINT:-https://api.test.smartsheet.com/2.0}
      - ALLOW_DELETE_TOOLS=${ALLOW_DELETE_TOOLS:-false}
      - NODE_ENV=development
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    profiles:
      - dev
    networks:
      - smar-mcp-network

networks:
  smar-mcp-network:
    driver: bridge
